version: '3.8'
services:
  # Database Service
  postgres:
    image: postgres:14
    container_name: ssemail_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ssemail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache and Queue Service
  redis:
    image: redis:6.2-alpine
    container_name: ssemail_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: